WebApplication1/WebApplication1/Controllers/RabbitMqController.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using RabbitMQ.Client;
using WebApplication1.Service;
using WebApplication1.Service.Interface;

namespace WebApplication1.Controllers
{
    public class RabbitMqController : Controller
    {
        public IActionResult PushMQIndex()
        {
            return View();
        }

        public IActionResult PushDisbursementOrder(MqEventCreateDto eventDto)
        {
            try
            {
                ConnectionFactory factory = new ConnectionFactory
                {
                    HostName = eventDto.MQIP,
                    UserName = "guest",
                    Password = "guest",
                    VirtualHost = "/",
                    Port = 5672,
                };
                var mqConnection = new DefaultRabbitMQPersistentConnection(factory);
                var eventBus = new EventBusRabbitMq(mqConnection);

                if (eventDto.Type == 0)
                {
                    eventBus.Publish(new CreateDisbursementOrderIntegrationEvent()
                    {
                        DisbursementOrderId = eventDto.DisbursementOrderId,
                        MerchantId = eventDto.MerchantId
                    });
                }
                else if (eventDto.Type == 1)
                {
                    eventBus.Publish(new QueryDisbursementOrderIntegrationEvent()
                    {
                        DisbursementOrderId = eventDto.DisbursementOrderId,
                        MerchantId = eventDto.MerchantId
                    });
                }
                else
                {
                    return Json("MQ推送失敗，不明的Routing key");
                }

                mqConnection.Dispose();
                return Json("MqEventCreateDto 推送成功");
            }
            catch (Exception e)
            {
                return Json($"MqEventCreateDto 發生例外,{e}");
            }
        }
    }

    public class MqEventCreateDto
    {
        [Required(ErrorMessage = "Mq服務IP必填")]
        public string MQIP { get; set; }
        public string DisbursementOrderId { get; set; }
        public string MerchantId { get; set; }
        /// <summary>
        /// 0:CreateDisbursementOrderIntegrationEvent
        /// 1:QueryDisbursementOrderIntegrationEvent
        /// </summary>
        public int Type { get; set; }
    }

    public class CreateDisbursementOrderIntegrationEvent
    {
        public string DisbursementOrderId { get; set; }
        public string MerchantId { get; set; }
    }
    public class QueryDisbursementOrderIntegrationEvent
    {
        public string DisbursementOrderId { get; set; }
        public string MerchantId { get; set; }
    }
}

WebApplication1/WebApplication1/Views/RabbitMq/PushMQIndex.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
@model WebApplication1.Controllers.MqEventCreateDto;
<body>

    <form class="form-horizontal" method="post" asp-controller="RabbitMq" asp-action="PushDisbursementOrder" id="form1" autocomplete="true" target="iframe">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">MQ訂單測試</h3>
                    </div>
                    <div class="box-body">
                        
                        <div class="form-group">
                            <label for="DisbursementOrderId" class="col-sm-3 control-label">MQ服務IP</label>
                            <div class="col-sm-5">
                                <input asp-for="MQIP" class="form-control" placeholder="192.168.50.121" value="" />
                                <span asp-validation-for="MQIP" class="text-danger field-validation-valid"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="DisbursementOrderId" class="col-sm-3 control-label">訂單ID</label>
                            <div class="col-sm-5">
                                <input asp-for="DisbursementOrderId" class="form-control" placeholder="DisbursementOrderId" value="" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="MerchantId" class="col-sm-3 control-label">商户ID</label>
                            <div class="col-sm-5">
                                <input asp-for="MerchantId" class="form-control" placeholder="MerchantId" value="" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Type" class="col-sm-3 control-label">MQ提交方式</label>
                            <div class="col-sm-5">
                                <select asp-for="Type" class="form-control"><option value ="0">建立代付訂單</option><option value="1">查詢訂單</option></select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-5">
                            <button id="createOrder" type="button" class="btn btn-success">提交</button>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">API回應</label>
                        <div class="col-sm-10">
                            <input id="apiResponse" class="form-control" value="" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <iframe id="iframe" name="iframe" style="display: none;"></iframe>

</body>
</html>
@section Scripts
{
    <script>
        $('#createOrder').click(function () {
            var $form = $("#form1");
            $.ajax({
                type: "POST",
                url: $form.attr('action'),
                data: $form.serialize(),
                success: function (response) {
                    $('#apiResponse').val(response);

                }
            });
        })

    </script>
}